python3 main.py \
    --train_data_file=train.csv \
    --data_dir=data/emnlp_news \
    --model_name_or_path=xlnet \
    --eval_data_file=test.csv \
    --model_type=xlnet \
    --do_train \
    --do_eval \
    --data_dir=./data \
    --max_seq_length=128 \
    --per_gpu_train_batch_size=256 \
    --learning_rate=2e-5 \
    --num_train_epochs=1.0 \
    --do_lower_case \
    --gradient_accumulation_steps=24 \
    --output_dir=./gan_results             
